INSERT INTO baseentity (dtype, realm, code, name, created, updated, status, capreqs) 
SELECT dtype, realm, code, name, created, updated, status, capreqs from question;

INSERT INTO baseentity_attribute (attributeCode, baseEntityCode, created, realm, updated, valueBoolean, valueDate, valueDateTime, valueDouble, valueInteger, valueLong, money, valueString, valueTime, weight,ATTRIBUTE_ID,BASEENTITY_ID,capreqs) 
SELECT 'attributeCode',q.code,q.created,q.realm,q.updated,null,null,null,null,null,null,null,q.attributeCode,null,null,attribute_id,b.id,q.capreqs from question q, baseentity b  where q.realm = b.realm and q.code = b.code;
INSERT INTO baseentity_attribute (attributeCode, baseEntityCode, created, realm, updated, valueBoolean, valueDate, valueDateTime, valueDouble, valueInteger, valueLong, money, valueString, valueTime, weight,ATTRIBUTE_ID,BASEENTITY_ID,capreqs)
SELECT 'directions',q.code,q.created,q.realm,q.updated,null,null,null,null,null,null,null,q.directions,null,null,attribute_id,b.id,q.capreqs from question q, baseentity b  where q.realm = b.realm and q.code = b.code;
INSERT INTO baseentity_attribute (attributeCode, baseEntityCode, created, realm, updated, valueBoolean, valueDate, valueDateTime, valueDouble, valueInteger, valueLong, money, valueString, valueTime, weight,ATTRIBUTE_ID,BASEENTITY_ID,capreqs)
SELECT 'helper',q.code,q.created,q.realm,q.updated,null,null,null,null,null,null,null,q.helper,null,null,attribute_id,b.id,q.capreqs from question q, baseentity b  where q.realm = b.realm and q.code = b.code;
INSERT INTO baseentity_attribute (attributeCode, baseEntityCode, created, realm, updated, valueBoolean, valueDate, valueDateTime, valueDouble, valueInteger, valueLong, money, valueString, valueTime, weight,ATTRIBUTE_ID,BASEENTITY_ID,capreqs)
SELECT 'html',q.code,q.created,q.realm,q.updated,null,null,null,null,null,null,null,q.html,null,null,attribute_id,b.id,q.capreqs from question q, baseentity b  where q.realm = b.realm and q.code = b.code;
INSERT INTO baseentity_attribute (attributeCode, baseEntityCode, created, realm, updated, valueBoolean, valueDate, valueDateTime, valueDouble, valueInteger, valueLong, money, valueString, valueTime, weight,ATTRIBUTE_ID,BASEENTITY_ID,capreqs)
SELECT 'icon',q.code,q.created,q.realm,q.updated,null,null,null,null,null,null,null,q.icon,null,null,attribute_id,b.id,q.capreqs from question q, baseentity b  where q.realm = b.realm and q.code = b.code;
INSERT INTO baseentity_attribute (attributeCode, baseEntityCode, created, realm, updated, valueBoolean, valueDate, valueDateTime, valueDouble, valueInteger, valueLong, money, valueString, valueTime, weight,ATTRIBUTE_ID,BASEENTITY_ID,capreqs)
SELECT 'mandatory',q.code,q.created,q.realm,q.updated,mandatory,null,null,null,null,null,null,null,null,null,attribute_id,b.id,q.capreqs from question q, baseentity b  where q.realm = b.realm and q.code = b.code;
INSERT INTO baseentity_attribute (attributeCode, baseEntityCode, created, realm, updated, valueBoolean, valueDate, valueDateTime, valueDouble, valueInteger, valueLong, money, valueString, valueTime, weight,ATTRIBUTE_ID,BASEENTITY_ID,capreqs)
SELECT 'oneshot',q.code,q.created,q.realm,q.updated,oneshot,null,null,null,null,null,null,null,null,null,attribute_id,b.id,q.capreqs from question q, baseentity b  where q.realm = b.realm and q.code = b.code;
INSERT INTO baseentity_attribute (attributeCode, baseEntityCode, created, realm, updated, valueBoolean, valueDate, valueDateTime, valueDouble, valueInteger, valueLong, money, valueString, valueTime, weight,ATTRIBUTE_ID,BASEENTITY_ID,capreqs)
SELECT 'placeholder',q.code,q.created,q.realm,q.updated,null,null,null,null,null,null,null,q.placeholder,null,null,attribute_id,b.id,q.capreqs from question q, baseentity b  where q.realm = b.realm and q.code = b.code;
INSERT INTO baseentity_attribute (attributeCode, baseEntityCode, created, realm, updated, valueBoolean, valueDate, valueDateTime, valueDouble, valueInteger, valueLong, money, valueString, valueTime, weight,ATTRIBUTE_ID,BASEENTITY_ID,capreqs)
SELECT 'readonly',q.code,q.created,q.realm,q.updated,readonly,null,null,null,null,null,null,null,null,null,attribute_id,b.id,q.capreqs from question q, baseentity b  where q.realm = b.realm and q.code = b.code;

INSERT INTO baseentity (dtype, realm, code, name, created, updated, status, capreqs)
SELECT 'QuestionQuestion', realm, concat(sourceCode,'|',targetCode), concat(sourceCode,'|',targetCode), created, updated, 0, capreqs from question_question;

INSERT INTO baseentity_attribute (attributeCode, baseEntityCode, created, realm, updated, valueBoolean, valueDate, valueDateTime, valueDouble, valueInteger, valueLong, money, valueString, valueTime, weight,ATTRIBUTE_ID,BASEENTITY_ID,capreqs)
SELECT 'parentCode',CONCAT(sourceCode,'|',targetCode),qq.created,qq.realm,qq.updated,null,null,null,null,null,null,null,sourceCode,null,null,q.attribute_id,b.id,qq.capreqs from question_question qq, question q, baseentity b where qq.SOURCE_ID = q.id and q.code = b.code and q.realm = b.realm;
INSERT INTO baseentity_attribute (attributeCode, baseEntityCode, created, realm, updated, valueBoolean, valueDate, valueDateTime, valueDouble, valueInteger, valueLong, money, valueString, valueTime, weight,ATTRIBUTE_ID,BASEENTITY_ID,capreqs)
SELECT 'childCode',CONCAT(sourceCode,'|',targetCode),qq.created,qq.realm,qq.updated,null,null,null,null,null,null,null,targetCode,null,null,q.attribute_id,b.id,qq.capreqs from question_question qq, question q, baseentity b where qq.SOURCE_ID = q.id and q.code = b.code and q.realm = b.realm;
INSERT INTO baseentity_attribute (attributeCode, baseEntityCode, created, realm, updated, valueBoolean, valueDate, valueDateTime, valueDouble, valueInteger, valueLong, money, valueString, valueTime, weight,ATTRIBUTE_ID,BASEENTITY_ID,capreqs)
SELECT 'createOnTrigger',CONCAT(sourceCode,'|',targetCode),qq.created,qq.realm,qq.updated,createOnTrigger,null,null,null,null,null,null,null,null,null,q.attribute_id,b.id,qq.capreqs from question_question qq, question q, baseentity b where qq.SOURCE_ID = q.id and q.code = b.code and q.realm = b.realm;
INSERT INTO baseentity_attribute (attributeCode, baseEntityCode, created, realm, updated, valueBoolean, valueDate, valueDateTime, valueDouble, valueInteger, valueLong, money, valueString, valueTime, weight,ATTRIBUTE_ID,BASEENTITY_ID, capreqs)
SELECT 'dependency',CONCAT(sourceCode,'|',targetCode),qq.created,qq.realm,qq.updated,null,null,null,null,null,null,null,dependency,null,null,q.attribute_id,b.id,qq.capreqs from question_question qq, question q, baseentity b where qq.SOURCE_ID = q.id and q.code = b.code and q.realm = b.realm;
INSERT INTO baseentity_attribute (attributeCode, baseEntityCode, created, realm, updated, valueBoolean, valueDate, valueDateTime, valueDouble, valueInteger, valueLong, money, valueString, valueTime, weight,ATTRIBUTE_ID,BASEENTITY_ID,capreqs)
SELECT 'disabled',CONCAT(sourceCode,'|',targetCode),qq.created,qq.realm,qq.updated,disabled,null,null,null,null,null,null,null,null,null,q.attribute_id,b.id,qq.capreqs from question_question qq, question q, baseentity b where qq.SOURCE_ID = q.id and q.code = b.code and q.realm = b.realm;
INSERT INTO baseentity_attribute (attributeCode, baseEntityCode, created, realm, updated, valueBoolean, valueDate, valueDateTime, valueDouble, valueInteger, valueLong, money, valueString, valueTime, weight,ATTRIBUTE_ID,BASEENTITY_ID,capreqs)
SELECT 'formTrigger',CONCAT(sourceCode,'|',targetCode),qq.created,qq.realm,qq.updated,formTrigger,null,null,null,null,null,null,null,null,null,q.attribute_id,b.id,qq.capreqs from question_question qq, question q, baseentity b where qq.SOURCE_ID = q.id and q.code = b.code and q.realm = b.realm;
INSERT INTO baseentity_attribute (attributeCode, baseEntityCode, created, realm, updated, valueBoolean, valueDate, valueDateTime, valueDouble, valueInteger, valueLong, money, valueString, valueTime, weight,ATTRIBUTE_ID,BASEENTITY_ID,capreqs)
SELECT 'hidden',CONCAT(sourceCode,'|',targetCode),qq.created,qq.realm,qq.updated,hidden,null,null,null,null,null,null,null,null,null,q.attribute_id,b.id,qq.capreqs from question_question qq, question q, baseentity b where qq.SOURCE_ID = q.id and q.code = b.code and q.realm = b.realm;
INSERT INTO baseentity_attribute (attributeCode, baseEntityCode, created, realm, updated, valueBoolean, valueDate, valueDateTime, valueDouble, valueInteger, valueLong, money, valueString, valueTime, weight,ATTRIBUTE_ID,BASEENTITY_ID,capreqs)
SELECT 'icon',CONCAT(sourceCode,'|',targetCode),qq.created,qq.realm,qq.updated,null,null,null,null,null,null,null,qq.icon,null,null,q.attribute_id,b.id,qq.capreqs from question_question qq, question q, baseentity b where qq.SOURCE_ID = q.id and q.code = b.code and q.realm = b.realm;
INSERT INTO baseentity_attribute (attributeCode, baseEntityCode, created, realm, updated, valueBoolean, valueDate, valueDateTime, valueDouble, valueInteger, valueLong, money, valueString, valueTime, weight,ATTRIBUTE_ID,BASEENTITY_ID,capreqs)
SELECT 'mandatory',CONCAT(sourceCode,'|',targetCode),qq.created,qq.realm,qq.updated,qq.mandatory,null,null,null,null,null,null,null,null,null,q.attribute_id,b.id,qq.capreqs from question_question qq, question q, baseentity b where qq.SOURCE_ID = q.id and q.code = b.code and q.realm = b.realm;
INSERT INTO baseentity_attribute (attributeCode, baseEntityCode, created, realm, updated, valueBoolean, valueDate, valueDateTime, valueDouble, valueInteger, valueLong, money, valueString, valueTime, weight,ATTRIBUTE_ID,BASEENTITY_ID,capreqs)
SELECT 'oneshot',CONCAT(sourceCode,'|',targetCode),qq.created,qq.realm,qq.updated,qq.oneshot,null,null,null,null,null,null,null,null,null,q.attribute_id,b.id,qq.capreqs from question_question qq, question q, baseentity b where qq.SOURCE_ID = q.id and q.code = b.code and q.realm = b.realm;
INSERT INTO baseentity_attribute (attributeCode, baseEntityCode, created, realm, updated, valueBoolean, valueDate, valueDateTime, valueDouble, valueInteger, valueLong, money, valueString, valueTime, weight,ATTRIBUTE_ID,BASEENTITY_ID,capreqs)
SELECT 'readonly',CONCAT(sourceCode,'|',targetCode),qq.created,qq.realm,qq.updated,qq.readonly,null,null,null,null,null,null,null,null,null,q.attribute_id,b.id,qq.capreqs from question_question qq, question q, baseentity b where qq.SOURCE_ID = q.id and q.code = b.code and q.realm = b.realm;
INSERT INTO baseentity_attribute (attributeCode, baseEntityCode, created, realm, updated, valueBoolean, valueDate, valueDateTime, valueDouble, valueInteger, valueLong, money, valueString, valueTime, weight,ATTRIBUTE_ID,BASEENTITY_ID,capreqs)
SELECT 'version',CONCAT(sourceCode,'|',targetCode),qq.created,qq.realm,qq.updated,null,null,null,null,null,`version`,null,null,null,null,q.attribute_id,b.id,qq.capreqs from question_question qq, question q, baseentity b where qq.SOURCE_ID = q.id and q.code = b.code and q.realm = b.realm;
INSERT INTO baseentity_attribute (attributeCode, baseEntityCode, created, realm, updated, valueBoolean, valueDate, valueDateTime, valueDouble, valueInteger, valueLong, money, valueString, valueTime, weight,ATTRIBUTE_ID,BASEENTITY_ID,capreqs)
SELECT 'weight',CONCAT(sourceCode,'|',targetCode),qq.created,qq.realm,qq.updated,null,null,null,weight,null,null,null,null,null,null,q.attribute_id,b.id,qq.capreqs from question_question qq, question q, baseentity b where qq.SOURCE_ID = q.id and q.code = b.code and q.realm = b.realm;
