ALTER TABLE baseentity DROP PRIMARY KEY;
ALTER TABLE baseentity ADD CONSTRAINT pri_key PRIMARY KEY (realm,code);
ALTER TABLE baseentity DROP COLUMN dtype;
DROP TABLE IF EXISTS context;
ALTER TABLE baseentity DROP COLUMN id;
