version: '2'

services:
  nginx:
    image: jwilder/nginx-proxy:latest
    hostname: nginx
    ports:
      - 80:80
  #    - 443:443
    networks:
      - mainproxy    
    environment:
      - SKIP_HTTPS_REDIRECT=true
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/vhost.d:/etc/nginx/vhost.d
      - ./nginx/html:/usr/share/nginx/html
      - ./nginx/certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro

  imageproxy:
    image: willnorris/imageproxy:v0.7.0
    ports:
      - "46243:8080"
    command: -cache /tmp/imageproxy -addr 0.0.0.0:8080 -scaleUp true


  mysql:
    image: channel40/mysql:latest2 
    environment:
      - MYSQL_URL=mysql
      - MYSQL_DB=gennydb
      - MYSQL_PORT=3306
      - MYSQL_ALLOW_EMPTY=
      - MYSQL_RANDOM_ROOT_PASSWORD=no
      - MYSQL_DATABASE=gennydb
      - MYSQL_USER=genny
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=password
    container_name: mysql
    env_file:
      - ${ENV_FILE}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - mainproxy
    ports:
      - 3310:3306
    restart: unless-stopped


  qwanda-service:
    depends_on:
      - mysql
      - keycloak
    image: gennyproject/wildfly-qwanda-service:latest
    container_name: qwanda-service
    volumes:
      - ./realm:/opt/realm
      - ./google_credentials:/root/.genny/sheets.googleapis.com-java-quickstart/
    env_file:
      - ${ENV_FILE}
    environment:
      - VIRTUAL_HOST=qwanda-service.*
      - VIRTUAL_PORT=8080
      - VIRTUAL_PROTO=http
      - CERT_NAME=genny.live
    ports:
      - "8280:8080"
      - "8887:8787"
    links:
      - mysql:mysql
      - keycloak:keycloak
    restart: unless-stopped
    networks:
      - mainproxy

  keycloak:
    image: gennyproject/keycloak:latest
    container_name: keycloak
    env_file:
      - ${ENV_FILE}
    environment:
      - VIRTUAL_HOST=keycloak.*,bouncer.*
      - VIRTUAL_PORT=8080
      - VIRTUAL_PROTO=http
      - CERT_NAME=genny.live
#      - IMPORTEXPORT=EXPORT
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=Outcome2016KeycloakAdmin
      - MYSQL_URL=mysql
      - MYSQL_PORT=3306
      - MYSQL_DB=keycloakdb
      - MYSQL_USERNAME=keycloak
      - MYSQL_PASSWORD=Outcome2016KeycloakAdmin
    volumes:
#      - /opt/jboss/backup:/opt/jboss/backup
      - ../keycloak-themes/themes:/opt/jboss/keycloak/themes
      - ./realm:/tmp/realm
      #- ./realm:/tmp/realm
      #- ./keycloak-themes/themes:/opt/jboss/keycloak/themes
    networks:
      - mainproxy
    ports:
      - 8180:8080
    command: -b 0.0.0.0

  bridge:
    image: gennyproject/bridge:latest
    container_name: bridge
    volumes:
      - ./realm:/opt/realm
    env_file:
      - ${ENV_FILE}
    environment:
      - VIRTUAL_HOST=bridge.genny.live
      - VIRTUAL_PORT=8088
      - VIRTUAL_PROTO=http
      - CERT_NAME=genny.live
    networks:
      - mainproxy
    links:
      - qwanda-service:qwanda-service
      - keycloak
    ports:
      - 8088:8088
      - 5701:5701
      - 4001:15701
    command: java -Dvertx.metrics.options.enabled=true -Dvertx.options.blockedThreadCheckInterval=2147483647 -jar /service.jar -cluster

  rulesservice:
    image: gennyproject/rulesservice:latest
    container_name:  rulesservice
    volumes:
      - ./realm:/opt/realm
#      - ./rules:/rules
      - ./rules:/rules2
    links:
      - bridge:bridge
      - qwanda-service:qwanda-service
      - keycloak
    environment:
      - RULES_DIR=/rules
      - VIRTUAL_HOST=rulesservice.genny.live
      - VIRTUAL_PORT=8089
      - VIRTUAL_PROTO=http
      - CERT_NAME=genny.live
    env_file:
      - ${ENV_FILE}
    ports:
       - 8089:8089
#      - 8880:8080
      - 5702:5702
      - 4002:15702
    depends_on:
      - messages
      - bridge
      - qwanda-service
    networks:
      - mainproxy
    restart: always
    command: java  -Dvertx.options.blockedThreadCheckInterval=2147483647 -jar /service.jar -cluster

  social:
    image: gennyproject/social:latest
    container_name: social
    volumes:
      - ./realm:/opt/realm
    env_file:
      - ${ENV_FILE}
    environment:
      - VIRTUAL_HOST=social.genny.live
      - VIRTUAL_PORT=8083
      - VIRTUAL_PROTO=http
      - CERT_NAME=genny.live
    networks:
      - mainproxy
    links:
      - qwanda-service:qwanda-service
      - keycloak
    depends_on:
      - qwanda-service
    ports:
      - 8083:8083
    command: java -Djava.net.preferIPv6Addresses=false -Djava.net.preferIPv4Stack=true -Djava.net.preferIPv4Addresses=true -Dvertx.hazelcast.config=/cluster.xml -DdockerNetworkNames=mainproxy -DdockerServiceNames=gennymain_hazelcast-genny -DhazelcastPeerPort=5701 -jar /service.jar



  messages:
    image: gennyproject/messages:latest
    container_name:  messages
    volumes:
      - ./realm:/opt/realm
      - ./google_credentials:/root/.genny/sheets.googleapis.com-java-quickstart/
      - ./google_credentials/drive:/root/.genny/credentials/credentials-genny/drive/
    links:
      - qwanda-service:qwanda-service
      - keycloak
    env_file:
      - ${ENV_FILE}
    ports:
      - 5709:5709
      - 4003:15709
    depends_on:
      - bridge
      - qwanda-service
    networks:
      - mainproxy
    restart: always
    command: java -Djava.net.preferIPv6Addresses=false -Djava.net.preferIPv4Stack=true -Djava.net.preferIPv4Addresses=true -Dvertx.hazelcast.config=/cluster.xml -DdockerNetworkNames=mainproxy -DdockerServiceNames=gennymain_hazelcast-genny -DhazelcastPeerPort=5701 -jar /service.jar

  payments:
     image: gennyproject/payments:latest
     container_name: payments
     env_file:
      - ${ENV_FILE}
     ports:
       - "3456:3456"
     networks:
       - mainproxy

  uppy:
     image: gennyproject/uppy:latest
     container_name: uppy
     env_file:
       - ${ENV_FILE}
     ports:
       - "3020:3020"
     networks:
       - mainproxy

  layout-cache:
    image: gennyproject/layout-cache:latest
    container_name: layout-cache
    environment:
      - LAYOUT_REPO=https://github.com/genny-project/layouts.git
      - NODE_ENV=staging
    ports:
      - "2223:2223"
    networks:
      - mainproxy

  camelot-pdfgenerator:
    image: matthayward1997/camelot:latest
    container_name: camelot-pdfgenerator
    ports:
      - "7331:7331"
    networks:
      - mainproxy

volumes:
  mysql_data:
  maildata:
    driver: local
  mailstate:
    driver: local
networks:
  mainproxy:
    driver: bridge

#
