version: '2'

services:
 redis:
    image: redis:alpine
    container_name: redis
    networks:
      - mainproxy
    restart: always


  mysql:
    image: mariadb
    environment:
      - MYSQL_URL=mysql
      - MYSQL_DB=gennydb
      - MYSQL_PORT=3306
      - MYSQL_ALLOW_EMPTY=
      - MYSQL_RANDOM_ROOT_PASSWORD=no
      - MYSQL_DATABASE=gennydb
      - MYSQL_USER=genny
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=password
    container_name: mysql
    env_file:
      - ${ENV_FILE}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - mainproxy
    ports:
      - 3310:3306
    restart: unless-stopped



  qwanda-service:
    depends_on:
      - mysql
      - keycloak
    #image: gennyproject/qwanda-service:latest
    image: gennyproject/wildfly-qwanda-service:latest
    container_name: qwanda-service
    volumes:
      - ./realm:/opt/realm
      - ./google_credentials:/root/.genny/sheets.googleapis.com-java-quickstart/
    env_file:
      - ${ENV_FILE}
    ports:
      - "8280:8080"
      - "8887:8787"
    links:
      - mysql:mysql
      - keycloak:keycloak
    restart: unless-stopped
    networks:
      - mainproxy

  keycloak:
    image: gennyproject/keycloak:latest
    container_name: keycloak
    env_file:
      - ${ENV_FILE}
    environment:
#      - IMPORTEXPORT=EXPORT
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=Outcome2016KeycloakAdmin
      - MYSQL_URL=mysql
      - MYSQL_PORT=3306
      - MYSQL_DB=keycloakdb
      - MYSQL_USERNAME=keycloak
      - MYSQL_PASSWORD=Outcome2016KeycloakAdmin
    volumes:
#      - /opt/jboss/backup:/opt/jboss/backup
      - ../keycloak-themes/themes:/opt/jboss/keycloak/themes
      - ./realm:/tmp/realm
      #- ./realm:/tmp/realm
      #- ./keycloak-themes/themes:/opt/jboss/keycloak/themes
    networks:
      - mainproxy
    ports:
      - 8180:8080
    command: -b 0.0.0.0

  bridge:
    image: gennyproject/bridge:latest
    container_name: bridge
    volumes:
      - ./realm:/opt/realm
    env_file:
      - ${ENV_FILE}
    networks:
      - mainproxy
    links:
      - qwanda-service:qwanda-service
      - keycloak
    ports:
      - 8088:8088
#      - 5701:5701
#      - 4001:15701
    command: java -Dvertx.options.blockedThreadCheckInterval=2147483647 -Djava.net.preferIPv6Addresses=false -Djava.net.preferIPv4Stack=true -Djava.net.preferIPv4Addresses=true -Dvertx.hazelcast.config=/cluster.xml -DdockerNetworkNames=mainproxy -DdockerServiceNames=gennymain_hazelcast-genny -DhazelcastPeerPort=5701 -jar /service.jar -cluster

  rulesservice:
    image: gennyproject/rulesservice:latest
    container_name:  rulesservice
    volumes:
      - ./realm:/opt/realm
#      - ./rules:/rules
      - ./rules:/rules2
    links:
      - bridge:bridge
      - qwanda-service:qwanda-service
      - keycloak
    environment:
      -  RULES_DIR=/rules
    env_file:
      - ${ENV_FILE}
#    ports:
#      - 8880:8080
#      - 5702:5702
#      - 4002:15702
    depends_on:
      - messages
      - bridge
      - qwanda-service
    networks:
      - mainproxy
    restart: always
    command: java  -Dvertx.options.blockedThreadCheckInterval=2147483647 -Djava.net.preferIPv6Addresses=false -Djava.net.preferIPv4Stack=true -Djava.net.preferIPv4Addresses=true -Dvertx.hazelcast.config=/cluster.xml -DdockerNetworkNames=mainproxy -DdockerServiceNames=gennymain_hazelcast-genny -DhazelcastPeerPort=5701 -jar /service.jar -cluster


  messages:
    image: gennyproject/messages:latest
    container_name:  messages
    volumes:
      - ./realm:/opt/realm
      - ./google_credentials:/root/.genny/sheets.googleapis.com-java-quickstart/
      - ./google_credentials/drive:/root/.genny/credentials/credentials-genny/drive/
    links:
      - qwanda-service:qwanda-service
      - keycloak
    env_file:
      - ${ENV_FILE}
    ports:
      - 5709:5709
      - 4003:15709
    depends_on:
      - bridge
      - qwanda-service
    networks:
      - mainproxy
    restart: always
    command: java -Djava.net.preferIPv6Addresses=false -Djava.net.preferIPv4Stack=true -Djava.net.preferIPv4Addresses=true -Dvertx.hazelcast.config=/cluster.xml -DdockerNetworkNames=mainproxy -DdockerServiceNames=gennymain_hazelcast-genny -DhazelcastPeerPort=5701 -jar /service.jar

  payments:
     image: gennyproject/payments:latest
     container_name: payments
     env_file:
      - ${ENV_FILE}
     ports:
       - "3456:3456"
     networks:
       - mainproxy


#  layout-cache:
#    image: gennyproject/layout-cache:latest
#    container_name: layout-cache
#    environment:
#      - LAYOUT_REPO=https://github.com/genny-project/layouts.git
#    ports:
#      - "2223:2223"
#    networks:
#      - mainproxy


volumes:
  mysql_data:
  maildata:
    driver: local
  mailstate:
    driver: local
networks:
  mainproxy:
    driver: bridge

#
