version: '2.3'

services:
  zookeeper:
    image: strimzi/kafka:latest-kafka-2.5.0
    command: [
      "sh", "-c",
      "bin/zookeeper-server-start.sh config/zookeeper.properties"
    ]
    ports:
      - "2181:2181"
    networks:
      - mainproxy
    environment:
      LOG_DIR: /tmp/logs

  kafka:
    image: strimzi/kafka:latest-kafka-2.5.0
    hostname: kafka
    container_name: kafka
    command: [
      "sh", "-c",
      "bin/kafka-server-start.sh config/server.properties --override listeners=$${KAFKA_LISTENERS} --override advertised.listeners=$${KAFKA_ADVERTISED_LISTENERS} --override zookeeper.connect=$${KAFKA_ZOOKEEPER_CONNECT} --override  message.max.bytes=1147483648" 
    ]
    depends_on:
      - zookeeper
    networks:
      - mainproxy
    ports:
      - "9092:9092"
    environment:
      LOG_DIR: "/tmp/logs"
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    healthcheck:
      test: ["CMD", "nc", "-vz", "localhost", "9092"]
#      test:
#        ["CMD", "kafka-topics.sh", "--list", "--zookeeper", "zookeeper:2181"]
      interval: 30s
      timeout: 10s
      retries: 4

  infinispan:
    image: infinispan/server:13.0
    container_name: infinispan
    environment:
      - USER=genny
      - PASS=password
    ports:
      - 11222:11222
    networks:
      - mainproxy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://infinispan:11222/console/welcome"]
      interval: 10s
      timeout: 50s
      start_period: 20s
      retries: 100 


  nginx:
    image: jwilder/nginx-proxy:alpine
    hostname: nginx
    depends_on:
      bridge:
        condition: service_healthy
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    networks:
      - mainproxy
    environment:
      - SKIP_HTTPS_REDIRECT=true
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:delegated
      - ./nginx/vhost.d:/etc/nginx/vhost.d:delegated
      - ./nginx/html:/usr/share/nginx/html:delegated
#      - ../stt-unity/safeTrafficTown/Build:/usr/share/nginx/html/unity
      - ./nginx/certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
#    healthcheck:
#      test: ["CMD", "curl", "--fail", "http://nginx.host.com"]
#      interval: 1m30s
#      timeout: 10s
#      retries: 3

  imageproxy:
    image: willnorris/imageproxy:v0.10.0
    container_name: imageproxy
    ports:
      - "46243:8080"
    networks:
      - mainproxy
    command: -cache /tmp/imageproxy -addr 0.0.0.0:8080 -scaleUp true


  alyson:
    image: gennyproject/alyson:latest
    container_name: alyson
    depends_on:
      - bridge
    ports:
      - "7000:8080"
    environment:
      - VIRTUAL_HOST=internmatch.genny.life,stt.genny.life,alyson.*
      - VIRTUAL_PORT=8080
      - REACT_BRIDGE_HOST=http://bridge.genny.life
      - NODE_ENV=production
    env_file:
      - ${ENV_FILE}
    networks:
      - mainproxy
    restart: always


  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      - MINIO_ACCESS_KEY=AKIAIOSFODNN7EXAMPLE
      - MINIO_SECRET_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
    env_file:
      - ${ENV_FILE}
    volumes:
      - minio_data:/data:delegated
      - minio_conf:/root/.minio:delegated
    networks:
      - mainproxy
    ports:
      - 9000:9000
    command: server /data

  genny-proxy:
    image: gennyproject/genny-proxy:latest
    container_name: genny-proxy 
    user: root
    depends_on:
      qwanda-service:
        condition: service_healthy
    volumes:
      - abn_tmp:/tmp/
    environment:
      - CORS_LIST=https://internmatch.genny.life,http://localhost:3000,https://stt.genny.life
    networks:
      - mainproxy
    ports:
      - 8483:8080

  media-proxy:
    image: gennyproject/media-proxy:latest
    container_name: media-proxy
    env_file:
      - ${ENV_FILE}
    environment:
      - KEYCLOAKURL=https://keycloak.gada.io/auth/realms
    networks:
      - mainproxy
    ports:
      - 9898:9898
    command: java -jar /service.jar

  mysql:
    image:  mysql:8.0.25 
#    image:  gennyproject/mysql:8x 
    container_name: mysql
    environment:
      - MYSQL_URL=mysql
      - MYSQL_DB=gennydb
      - MYSQL_PORT=3306
      - MYSQL_ALLOW_EMPTY=
      - MYSQL_DATABASE=gennydb
      - MYSQL_USER=genny
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=password
    env_file:
      - ${ENV_FILE}
    volumes:
      - mysql_data:/var/lib/mysql:delegated
    networks:
      - mainproxy
    ports:
      - 3310:3306
    command: --sql_mode="" --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-time-zone="+00:00"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    restart: unless-stopped

  bootq:
    depends_on:
      mysql:
        condition: service_healthy
      kafka:
        condition: service_healthy
      infinispan:
        condition: service_healthy
    image: gennyproject/bootq:latest
    container_name: bootq 
    volumes:
      - ./google_credentials:/root/.genny/sheets.googleapis.com-java-quickstart
    env_file:
      - ${ENV_FILE}
    environment:
      - GOOGLE_SVC_ACC_PATH=/root/.genny/sheets.googleapis.com-java-quickstart/token-secret-service-account.json
      - CLEANUP_TASK_AND_BEATTRFORM=false
      - MYSQL_USER=genny
      - MYSQL_PASSWORD=password
      - FULL_MYSQL_URL=mysql/gennydb?serverTimezone=UTC
      - REACT_APP_QWANDA_API_URL=http://qwanda-service:8080
    ports:
      - "8480:8080"
      - "8487:5005"
    links:
      - mysql:mysql
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/version"]
      interval: 10s
      timeout: 10s
      retries: 100    
    restart: unless-stopped
    networks:
      - mainproxy


  qwanda-service:
    depends_on:
      mysql:
        condition: service_healthy
      kafka:
        condition: service_healthy
      infinispan:
        condition: service_healthy
      #keycloak:
      #  condition: service_healthy
    image: gennyproject/wildfly-qwanda-service:latest
    container_name: qwanda-service
    volumes:
      - ./google_credentials:/root/.genny/sheets.googleapis.com-java-quickstart
      - abn_tmp:/tmp/
    env_file:
      - ${ENV_FILE}
    environment:
      - PROJECT_REALM=internmatch
      - USE_VERTX_UTILS=true
      - FORCE_EVENTBUS_USE_API=FALSE
      - FORCE_CACHE_USE_API=FALSE
      - VIRTUAL_HOST=qwanda-service.*,api.*
      - IS_CACHE_SERVER=true
      - JAVA_OPTS=-Xms2048m -Xmx2048m -Djava.net.preferIPv4Stack=true -Dsun.rmi.dgc.client.gcInterval=1800000 -Dsun.rmi.dgc.server.gcInterval=1800000  -server
      - ADMIN_USERNAME=GENNY 
      - ADMIN_PASSWORD=GENNY
      - VIRTUAL_PORT=8080
      - VIRTUAL_PROTO=http
      - CERT_NAME=genny.life
      - LOAD_DDT_IN_STARTUP=TRUE
      - SEARCH_ALT=TRUE
      - SKIP_GITHUB_IN_STARTUP=TRUE
      - SKIP_GOOGLE_DOC_IN_STARTUP=FALSE
      - DEBUG=TRUE
      - DEBUG_SUSPEND=n
      - XMX=2048m
  #    - DEV_MODE=TRUE
      - DDTHOST=TRUE
  #    - DDT_URL=http://bridge:8089 
    ports:
      - "8280:8080"
      - "8887:8787"
      - "10003:10003"
    links:
      - mysql:mysql
        #- keycloak:keycloak
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/version"]
      interval: 10s
      timeout: 10s
      retries: 100    
    restart: unless-stopped
    networks:
      - mainproxy


  bridge:
    image: gennyproject/bridge:latest
    depends_on:
      qwanda-service:
        condition: service_healthy
      kafka:
        condition: service_healthy
      infinispan:
        condition: service_healthy
      wildfly-rulesservice:
        condition: service_healthy
    container_name: bridge
    volumes:
      - ./realm:/opt/realm:delegated
    env_file:
      - ${ENV_FILE}
    environment:
      - ADMIN_USERNAME=GENNY 
      - ADMIN_PASSWORD=GENNY
      - VIRTUAL_HOST=bridge.genny.life
      - VIRTUAL_PORT=8088
      - KAFKA_URL=kafka:9092
      - VIRTUAL_PROTO=http
      - CERT_NAME=genny.life
      - KEYCLOAKURL=https://keycloak.gada.io/auth/realms
      - CACHE_SERVER_NAME=infinispan
      - DDTHOST=TRUE
      - API_PORT=8088
      - CACHE_API_PORT=8089
  #   - ZIP_MODE=TRUE
      - MODE_GZIP=TRUE
      - ZIP_MIN_THRESHOLD_BYTES=8000000
      - MEDIA_PROXY_URL=https://alyson.genny.life/web/public
  #    - DDT_URL=http://bridge:8089
  #    - DEV_MODE=TRUE
  #    - GENNYDEV=TRUE
  #    - GENNY_DEV=TRUE
    networks:
      - mainproxy
    ports:
      - 8088:8088
      - 8790:5005
      - 8089:8089
      - 5701:5701
      - 10001:10001
#      - 4001:15701
    command: java  -jar /deployments/service.jar 
#    command: java  -Xdebug -Xrunjdwp:transport=dt_socket,address=8787,server=y,suspend=n  -Dvertx.metrics.options.enabled=true -Dvertx.options.blockedThreadCheckInterval=2147483647 -jar /service.jar 
#    command: java -agentpath:/usr/local/YourKit-JavaProfiler-2019.8/bin/linux-x86-64/libyjpagent.so=port=10001,listen=all -Xdebug -Xrunjdwp:transport=dt_socket,address=8787,server=y,suspend=n  -Dvertx.options.blockedThreadCheckInterval=2147483647 -Dadmin.password=GENNY -Dadmin.username=GENNY -jar /deployments/service.jar 
#    command: java -jar -Dadmin.username=GENNY -Dadmin.password=GENNY /deployments/service.jar 
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8088/version"]
      interval: 10s
      timeout: 10s
      retries: 30


  wildfly-rulesservice:
    image: gennyproject/wildfly-rulesservice:latest
    depends_on:
      qwanda-service:
        condition: service_healthy
      mysql:
        condition: service_healthy
      kafka:
        condition: service_healthy
      infinispan:
        condition: service_healthy
    container_name: wildfly-rulesservice
    env_file:
      - ${ENV_FILE}
    volumes:
      - ./rules:/rules:delegated
      - ./google_credentials:/root/.genny/sheets.googleapis.com-java-quickstart/:delegated
    environment:
      - ADMIN_USERNAME=GENNY 
      - ADMIN_PASSWORD=GENNY
      - BULKPULL=FALSE
      - kafka.bootstrap.servers=kafka:9092
      - CERT_NAME=genny.life
      - DDT_URL=http://alyson7.genny.life:8089
      - DEBUG=TRUE
      - DEBUG_SUSPEND=n
      - DETECT_RULE_CHANGES=FALSE
      - DISABLE_LAYOUT_LOADING=TRUE
      - DROOLS_LOGLEVEL=ERROR
      - FORCE_EVENTBUS_USE_API=FALSE
      - FORCE_CACHE_USE_API=FALSE
      - CACHE_SERVER_NAME=infinispan
      - FRAMES_ON_DEMAND=FALSE
      - HAZELCAST_LOGLEVEL=ERROR
      - HIDE_RULE_STATES=TRUE
      - KEYCLOAK_LOGLEVEL=ERROR
      - PERSIST_RULES=TRUE
      - LOG_WORKFLOWS=FALSE
      - RULES_DIR=/rules
      - SEARCH_ALT=TRUE
      - USE_CONCURRENCY_MSGS=FALSE
      - USE_EVENT_QUEUE=TRUE
      - USE_JMS=TRUE
      - USE_EXECUTOR=TRUE
      - USE_SINGLETON=FALSE
      - VIRTUAL_HOST=rulesservice.*
      - VIRTUAL_PORT=8080
      - VIRTUAL_PROTO=http
      - XMX=3048m
      - XMS=3048m
      - JAVA_OPTS=-Xms3048m -Xmx3048m  -Djava.net.preferIPv4Stack=true -Dsun.rmi.dgc.client.gcInterval=1800000 -Dsun.rmi.dgc.server.gcInterval=1800000  -server 
      #- JAVA_OPTS=-Xms3048m -Xmx3048m -agentpath:/usr/local/jprofiler12.0.2/bin/linux-x64/libjprofilerti.so=nowait -Djava.net.preferIPv4Stack=true -Dsun.rmi.dgc.client.gcInterval=1800000 -Dsun.rmi.dgc.server.gcInterval=1800000  -server 
      - PDF_GEN_SERVICE_API_URL=http://internmatch.genny.life:7331
    ports:
      - "8380:8080"
      - "8987:8787"
      - "10002:10002"
      - "8849:8849"
  #  healthcheck:
  #    test: ["CMD", "curl", "-f", "http://localhost:8080/version"]
  #    interval: 10s
  #    timeout: 10s
  #    retries: 30    
    restart: unless-stopped
    networks:
      - mainproxy


  messages:
    image: gennyproject/messages:latest
    container_name:  messages
    volumes:
      - ./realm:/opt/realm:delegated
    env_file:
      - ${ENV_FILE}
    environment:
      - DDTHOST=TRUE
      - API_PORT=8089 
      - CACHE_API_PORT=8099
    ports:
      - 8791:8787
      - 5709:5709
      - 8189:8088
#      - 8199:8089
    depends_on:
      qwanda-service:
        condition: service_healthy
      bridge:
        condition: service_healthy
      kafka:
        condition: service_healthy
      infinispan:
        condition: service_healthy
    networks:
      - mainproxy
    restart: always
    command: java -jar /deployments/service.jar

  notes:
    image: gennyproject/notes:latest
    container_name: notes
    links:
      - mysql:mysql
    depends_on:
      bridge:
        condition: service_healthy
      mysql:
        condition: service_healthy
      kafka:
        condition: service_healthy
      infinispan:
        condition: service_healthy
    environment:
      - MYSQL_URL=mysql
      - MYSQL_DB=gennydb
      - MYSQL_USER=genny
      - MYSQL_PASSWORD=password
      - BRIDGE_URL=bridge.genny.life
      - NOTES_URL=http://alyson7.genny.life:8095
    ports:
      - "8195:8095"
    networks:
      - mainproxy
        #restart: always

  shleemy:
    image: gennyproject/shleemy:latest
    container_name: shleemy 
    links:
      - mysql:mysql
    depends_on:
      bridge:
        condition: service_healthy
      mysql:
        condition: service_healthy
      kafka:
        condition: service_healthy
      infinispan:
        condition: service_healthy
    environment:
      - FULL_MYSQL_URL=mysql/gennydb
      - MYSQL_URL=mysql
      - MYSQL_DB=gennydb
      - MYSQL_USER=genny
      - MYSQL_PASSWORD=password
      - BRIDGE_URL=bridge.genny.life
      - SHLEEMY_URL=http://alyson7.genny.life:8197
    ports:
      - "8197:8080"
    networks:
      - mainproxy
        #restart: always

  camelot-pdfgenerator:
    image: gennyproject/camelot:latest
    container_name: camelot-pdfgenerator
    ports:
      - "7331:7331"
    networks:
      - mainproxy


  mysqld-exporter:
    #image: quay.io/prometheus/mysqld-exporter
    image: prom/mysqld-exporter:latest
    command:
     - '--collect.info_schema.tablestats'
    container_name: mysqld-exporter
    environment:
      # add the mysql database here
      - DATA_SOURCE_NAME=exporter:exporter@(mysql:3306)/
    ports:
      - 9104:9104
    networks:
      - mainproxy
    depends_on:
      mysql:
        condition: service_healthy


volumes:
  abn_tmp:
  mysql_data:
  minio_conf:
  minio_data:
  maildata:
    driver: local
  mailstate:
    driver: local
networks:
  mainproxy:
    driver: bridge


