version: '2'

services:
  bsb-lookup:
    image: gennyproject/bsb-lookup:latest
    container_name: bsb-lookup
    ports:
      - 3333:3333
    networks:
      - mainproxy
    restart: always

  
  gennyql:
    image: gennyproject/gennyql
    container_name: gennyql
    networks:
      - mainproxy
    ports:
      - "8083:8084"
    restart: always
    command: java -jar /service.jar

  alyson:
    image: gennyproject/alyson:latest
    container_name: alyson
    ports:
      - "5000:80"
    env_file:
      - ${ENV_FILE}
    networks:
      - mainproxy
    restart: always

  mysql:
    image: mariadb
    environment:
      - MYSQL_URL=mysql
      - MYSQL_DB=gennydb
      - MYSQL_PORT=3306
      - MYSQL_ALLOW_EMPTY=
      - MYSQL_RANDOM_ROOT_PASSWORD=no
      - MYSQL_DATABASE=gennydb
      - MYSQL_USER=genny
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=password
    container_name: mysql
    env_file:
      - ${ENV_FILE}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - mainproxy
    ports:
      - 3310:3306
    restart: unless-stopped

  keycloak:
    image: gennyproject/keycloak:latest
    container_name: keycloak
    env_file:
      - ${ENV_FILE}
    environment:
#      - IMPORTEXPORT=EXPORT
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=Outcome2016KeycloakAdmin
      - MYSQL_URL=mysql
      - MYSQL_PORT=3306
      - MYSQL_DB=keycloakdb
      - MYSQL_USERNAME=keycloak
      - MYSQL_PASSWORD=Outcome2016KeycloakAdmin
    volumes:
#      - /opt/jboss/backup:/opt/jboss/backup
      - ../keycloak-themes/themes:/opt/jboss/keycloak/themes
      - ./realm:/tmp/realm
      #- ./realm:/tmp/realm
      #- ./keycloak-themes/themes:/opt/jboss/keycloak/themes
    networks:
      - mainproxy
    ports:
      - 8180:8080
    command: -b 0.0.0.0


#  keycloak:
#    image: gennyproject/keycloak:latest
#    container_name: keycloak
#    env_file:
#      - ${ENV_FILE}
#    environment:
#      - IMPORTEXPORT=EXPORT
#      - KEYCLOAK_USER=admin
#      - KEYCLOAK_PASSWORD=admin
#    volumes:
#      - ./realm:/tmp/realm
#    networks:
#      - mainproxy
#    ports:
#      - 8180:8080
#    command: -b 0.0.0.0

  qwanda-service:
    depends_on:
      - mysql
      - keycloak
    image: gennyproject/wildfly-qwanda-service:latest
    container_name: qwanda-service
    volumes:
      - ./realm:/opt/realm
      - ./google_credentials:/root/.genny/sheets.googleapis.com-java-quickstart/
    env_file:
      - ${ENV_FILE}
    ports:
      - "8280:8080"
      - "8887:8787"
    links:
      - mysql:mysql
      - keycloak:keycloak
    restart: unless-stopped
    networks:
      - mainproxy

  payments:
     image: gennyproject/payments:latest
     container_name: payments
     env_file:
      - ${ENV_FILE}
     ports:
       - "3456:3456"
     networks:
       - mainproxy

  layout-cache:
    image: gennyproject/layout-cache:latest
    container_name: layout-cache
    environment:
      - LAYOUT_REPO=https://github.com/genny-project/layouts.git
    ports:
      - "2223:2223"
    networks:
      - mainproxy



volumes:
  mysql_data:
  maildata:
    driver: local
  mailstate:
    driver: local
networks:
  mainproxy:
    driver: bridge
