version: '2.4'

services:

  nginx:
    image: jwilder/nginx-proxy:alpine
    container_name: nginx 
  #  image: nginx:alpine
  #  labels:
  #      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    hostname: nginx
    ports:
      - 80:80
      - 443:443
    networks:
      - mainproxy
    environment:
      - SKIP_HTTPS_REDIRECT=false
    volumes:
      - ./nginx/conf.d2:/etc/nginx/conf.d
      - ./nginx/vhost.d:/etc/nginx/vhost.d
      - ./nginx/html:/usr/share/nginx/html
      - ./nginx/certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
#    healthcheck:
#      test: ["CMD", "curl", "--fail", "http://nginx.host.com"]
#      interval: 1m30s
#      timeout: 10s
#      retries: 3


  alyson-v3:
    image: gennyproject/alyson-v3:latest
    container_name: alyson-v3
    ports:
      - "6000:8080"
    environment:
      - REACT_BRIDGE_HOST=http://bridge.genny.life
      - VIRTUAL_PORT=80
      - VIRTUAL_HOST=alyson-v3.*,v3.*
      - VIRTUAL_PROTO=http
      - CERT_NAME=genny.life
      - NODE_ENV=production
    env_file:
      - ${ENV_FILE}
    networks:
      - mainproxy
    restart: always

  alyson:
    image: gennyproject/alyson:latest
    container_name: alyson
    ports:
      - "5000:80"
    environment:
      - REACT_BRIDGE_HOST=http://bridge.genny.life
      - VIRTUAL_PORT=80
      - VIRTUAL_HOST=local.*,alyson.*,v2.*
      - VIRTUAL_PROTO=http
      - CERT_NAME=genny.life
    env_file:
      - ${ENV_FILE}
    networks:
      - mainproxy
    restart: always

  mysql:
    image: mysql:5.7
    #image: mariadb
    environment:
      - MYSQL_URL=mysql
      - MYSQL_DB=gennydb
      - MYSQL_PORT=3306
      - MYSQL_ALLOW_EMPTY=
      - MYSQL_RANDOM_ROOT_PASSWORD=no
      - MYSQL_DATABASE=gennydb
      - MYSQL_USER=genny
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=password
    container_name: mysql
    env_file:
      - ${ENV_FILE}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - mainproxy
    ports:
      - 3310:3306
    command: --sql_mode=""
    restart: unless-stopped

  keycloak:
    image: gennyproject/keycloak:latest
    container_name: keycloak
    env_file:
      - ${ENV_FILE}
    environment:
      - VIRTUAL_HOST=keycloak.*,bouncer.*
      - VIRTUAL_PORT=8080
      - VIRTUAL_PROTO=http
      - CERT_NAME=genny.life
#      - IMPORTEXPORT=EXPORT
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=Outcome2016KeycloakAdmin
      - MYSQL_URL=mysql
      - MYSQL_PORT=3306
      - MYSQL_DB=keycloakdb
      - MYSQL_USERNAME=keycloak
      - MYSQL_PASSWORD=Outcome2016KeycloakAdmin
    volumes:
  #    - ../keycloak-themes/themes:/opt/jboss/keycloak/themes
       - ./realm:/tmp/realm
       - ./data:/opt/jboss/keycloak/standalone/data
    networks:
      - mainproxy
    ports:
      - 8180:8080
    command: -b 0.0.0.0
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/auth"]
      interval: 10s
      timeout: 10s
      retries: 30


#  wildfly-rulesservice:
#    depends_on:
#      - mysql
#      - keycloak
#    image: gennyproject/wildfly-rulesservice:latest
#    container_name: wildfly-rulesservice 
#    volumes:
#      - ./realm:/opt/realm
#      - ./google_credentials:/root/.genny/sheets.googleapis.com-java-quickstart/
#    env_file:
#      - ${ENV_FILE}
#    volumes:
#      - ./realm:/opt/realm
#      - ./google_credentials:/root/.genny/sheets.googleapis.com-java-quickstart/
#      - ../rulesservice/src/main/resources/rules/rulesCurrent:/rules/rulesCurrent
#      - ../prj_${PROJECT_REALM}/rules:/rules/prj_${PROJECT_REALM}
#    environment:
#      - ADMIN_USERNAME=GENNY
 #     - ADMIN_PASSWORD=GENNY
 #     - RULES_DIR=/rules
 #     - VIRTUAL_HOST=rulesservice.*
 #     - VIRTUAL_PORT=8080
 #     - VIRTUAL_PROTO=http
 #     - CERT_NAME=genny.life
 #     - DEV_MODE=TRUE
 #     - CACHE_API_PORT=8989
 #     - DDTHOST=TRUE
 #   ports:
 #     - "8380:8080"
 #     - "8987:8787"
 #   links:
 #     - mysql:mysql
 #     - keycloak:keycloak
 #   restart: unless-stopped
 #   networks:
 #     - mainproxy
 #   healthcheck:
 #     test: ["CMD", "curl", "-f", "http://localhost:8080/version"]
 #     interval: 10s
 #     timeout: 10s
 #     retries: 30

  qwanda-service:
    depends_on:
      - mysql
      - keycloak
    image: gennyproject/wildfly-qwanda-service:latest
    container_name: qwanda-service
    volumes:
      - ./realm:/opt/realm
      - ./google_credentials:/root/.genny/sheets.googleapis.com-java-quickstart/
    env_file:
      - ${ENV_FILE}
    environment:
      - USE_VERTX_UTILS=true
      - FORCE_EVENTBUS_USE_API=TRUE
      - FORCE_CACHE_USE_API=FALSE
      - IS_CACHE_SERVER=TRUE
      - BRIDGE_SERVICE_API=http://bridge.genny.life:8088/api/service
      - CACHE_SERVER_NAME= bridge.genny.life
      - VIRTUAL_HOST=qwanda-service.*,api.*
      - VIRTUAL_PORT=8080
      - VIRTUAL_PROTO=http
      - DDT_URL= http://bridge.genny.life:8089
      - CERT_NAME=genny.life
      - SKIP_GOOGLE_DOC_IN_STARTUP=FALSE
      - LOAD_DDT_IN_STARTUP=TRUE
      - DEV_MODE=TRUE
      - CACHE_API_PORT=8089
  #    - GENNYDEV=TRUE
      - DDTHOST=TRUE
      - XMX=1024m
    ports:
      - "8280:8080"
      - "8887:8787"
  #    - "5706:5701"
    links:
      - mysql:mysql
      - keycloak:keycloak
    restart: unless-stopped
    networks:
      - mainproxy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/version"]
      interval: 10s
      timeout: 10s
      retries: 30

  payments:
     image: gennyproject/payments:latest
     container_name: payments
     env_file:
      - ${ENV_FILE}
     environment:
      - VIRTUAL_HOST=payments2.genny.life
      - VIRTUAL_PORT=3456
      - VIRTUAL_PROTO=http
      - CERT_NAME=genny.life
     ports:
      - "3456:3456"
      - "6543:6543"
     networks:
       - mainproxy

  layout-cache:
    image: gennyproject/layout-cache:latest
    container_name: layout-cache
    environment:
      - LAYOUT_REPO=https://github.com/genny-project/layouts.git
      - NODE_ENV=dev
      - VIRTUAL_HOST=layout-cache.genny.life
      - VIRTUAL_PORT=2223
      - VIRTUAL_PROTO=http
      - CERT_NAME=genny.life
      - GIT_SSH=${GIT_SSH}
      - SSH_PRIVATE_KEY=${SSH_PRIVATE_KEY}
    ports:
      - "2223:2223"
      - "2224:2224"
    networks:
      - mainproxy

  camelot-pdfgenerator:
    image: matthayward1997/camelot:latest
    container_name: camelot-pdfgenerator
    ports:
      - "7331:7331"
    networks:
      - mainproxy

  uppy:
     image: gennyproject/uppy:latest
     container_name: uppy
     env_file:
      - ${ENV_FILE}
     environment:
      - VIRTUAL_HOST=uppy.genny.life
      - VIRTUAL_PORT=3020
      - VIRTUAL_PROTO=http
      - CERT_NAME=genny.life
#     ports:
#       - "3020:3020"
     networks:
       - mainproxy


volumes:
  mysql_data:
  maildata:
    driver: local
  mailstate:
    driver: local
networks:
  mainproxy:
    driver: bridge
