version: '2'
 
services:

  alyson:
    image: gennyproject/alyson:latest
    container_name: alyson 
    volumes:
      - ./realm:/opt/realm
      - ./genny.env.json:/usr/share/nginx/html/genny.env.json
    depends_on:
      - bridge
    ports:
      - "5000:80"
    env_file:
      - ${ENV_FILE}
    networks:
      - mainproxy
    restart: always

  mysql:
    image: mysql:latest 
    container_name: mysql
    env_file:
      - ${ENV_FILE} 
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - mainproxy
    ports:
      - 3310:3306 
    restart: unless-stopped
 
 
  qwanda-service:
    depends_on:
      - mysql
      - keycloak
    command: ["./wait-for-it.sh"]
    image: gennyproject/qwanda-service:latest 
    container_name: qwanda-service 
    volumes:
      - ./realm:/opt/realm
    env_file:
      - ${ENV_FILE} 
    environment:
      - JAVA_OPT_KEYCLOAK_PATH=-Dswarm.keycloak.json.path=/realm/keycloak.json
    ports:
      - 8887:8787
      - 8280:8080
    links:
      - mysql:mysql
      - keycloak:keycloak
    restart: unless-stopped
    networks:
      - mainproxy

  keycloak:
    image: gennyproject/keycloak:working 
    container_name: keycloak 
    env_file:
      - ${ENV_FILE} 
#    environment:
#      - IMPORTEXPORT=EXPORT
#      - KEYCLOAK_USER=admin
#      - KEYCLOAK_PASSWORD=admin
    volumes:
      - ./realm:/tmp/realm 
    networks:
      - mainproxy
    ports:
      - 8180:8080
    command: -b 0.0.0.0  


  bridge:
    image: gennyproject/bridge:latest
    container_name: bridge 
    volumes:
      - ./realm:/opt/realm
    env_file:
      - ${ENV_FILE} 
    depends_on:
      - rulesservice
    networks:
      - mainproxy
    links:
      - qwanda-service:qwanda-service
      - keycloak
    ports:
      - 8081:8081  
      - 5701:5701
      - 4001:15701  
    command: java -Djava.net.preferIPv6Addresses=false -Djava.net.preferIPv4Stack=true -Djava.net.preferIPv4Addresses=true -Dvertx.hazelcast.config=/cluster.xml -DdockerNetworkNames=mainproxy -DdockerServiceNames=gennymain_hazelcast-genny -DhazelcastPeerPort=5701 -jar /service.jar
   
  rulesservice:
    image: gennyproject/rulesservice:latest
    container_name:  rulesservice 
    volumes:
      - ./realm:/opt/realm
      - ./rules:/rules
    links:
      # - bridge:bridge
      - qwanda-service:qwanda-service
      - keycloak
    env_file:
      - ${ENV_FILE} 
    ports:
      - 5702:5702
      - 4002:15702  
    # depends_on:
      # - bridge 
      # - qwanda-service
    networks:
      - mainproxy
    restart: always
    command: java -Djava.net.preferIPv6Addresses=false -Djava.net.preferIPv4Stack=true -Djava.net.preferIPv4Addresses=true -Dvertx.hazelcast.config=/cluster.xml -DdockerNetworkNames=mainproxy -DdockerServiceNames=gennymain_hazelcast-genny -DhazelcastPeerPort=5701 -jar /service.jar

#  social:
#    image: gennyproject/social:latest
#    container_name: social 
#    volumes:
#      - ./realm:/opt/realm
#    env_file:
#      - ${ENV_FILE} 
#    networks:
#      - mainproxy
#    links:
#      - qwanda-service:qwanda-service
#      - keycloak
#    ports:
#      - 8083:8083    
#    command: java -Djava.net.preferIPv6Addresses=false -Djava.net.preferIPv4Stack=true -Djava.net.preferIPv4Addresses=true -Dvertx.hazelcast.config=/cluster.xml -DdockerNetworkNames=mainproxy -DdockerServiceNames=gennymain_hazelcast-genny -DhazelcastPeerPort=5701 -jar /service.jar
#
#  scoring:
#    image: gennyproject/scoring:latest
#    container_name: scoring 
#    volumes:
#      - ./realm:/opt/realm
#    env_file:
#      - ${ENV_FILE} 
#    networks:
#      - mainproxy
#    links:
#      - qwanda-service:qwanda-service
#      - keycloak
#    ports:
#      - 8085:8085    
#    command: java -Djava.net.preferIPv6Addresses=false -Djava.net.preferIPv4Stack=true -Djava.net.preferIPv4Addresses=true -Dvertx.hazelcast.config=/cluster.xml -DdockerNetworkNames=mainproxy -DdockerServiceNames=gennymain_hazelcast-genny -DhazelcastPeerPort=5701 -jar /service.jar
#   
  kieclient: 
    image: gennyproject/kieclient:latest  
    container_name: kieclient
    links:
      - kie-server 
      - keycloak
    env_file:
      - ${ENV_FILE} 
    volumes:
      - ./realm:/opt/realm
    depends_on:
      - kie-server 
    ports:
      - 5703:5703
      - 4003:15703 
    networks:
      - mainproxy
    command: java -Djava.net.preferIPv6Addresses=false -Djava.net.preferIPv4Stack=true -Djava.net.preferIPv4Addresses=true -Dvertx.hazelcast.config=/cluster.xml -DdockerNetworkNames=mainproxy -DdockerServiceNames=gennymain_hazelcast-genny -DhazelcastPeerPort=5701 -jar /service.jar

  kie-server: 
    image: jboss/kie-server:latest  
    container_name: kie-server
    ports:
      - 8480:8080
    links:
      - qwanda-service
      - keycloak
    networks:
      - mainproxy

  kie-workbench: 
    image: jboss/jbpm-workbench:latest  
    container_name: kie-workbench
    ports:
      - 8580:8080
    links:
      - qwanda-service:qwanda-service
      - keycloak
      - kie-server
    networks:
      - mainproxy

  mail:
    image: tvial/docker-mailserver:latest
    hostname: mail
    domainname: domain.com
    container_name: mail
    ports:
    - "25:25"
    - "143:143"
    - "587:587"
    - "993:993"
    volumes:
    - maildata:/var/mail
    - mailstate:/var/mail-state
    - ./config/:/tmp/docker-mailserver/
    environment:
    - ENABLE_SPAMASSASSIN=1
    - ENABLE_CLAMAV=1
    - ENABLE_FAIL2BAN=1
    - ENABLE_POSTGREY=1
    - ONE_DIR=1
    - DMS_DEBUG=0
    cap_add:
    - NET_ADMIN
    networks:
      - mainproxy


volumes:
  mysql_data:
  maildata:
    driver: local
  mailstate:
    driver: local 
networks:
  mainproxy:
    driver: bridge 


