version: '2'
 
services:
  alyson:
    image: gennyproject/alyson:latest
    container_name: alyson
    ports:
      - "5000:80"
    env_file:
      - ${ENV_FILE}
    networks:
      - mainproxy
    restart: always

  kieserverdb:
    image: mysql:latest
    container_name: kieserverdb
    networks:
      - mainproxy
    ports:
      - 3320:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=kieserverdb
      - MYSQL_USER=genny
      - MYSQL_PASSWORD=password




  mysql:
    image: mysql:latest 
    container_name: mysql
    env_file:
      - ${ENV_FILE} 
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - mainproxy
    ports:
      - 3310:3306 
    restart: unless-stopped
 
 
#  qwanda-service:
#    depends_on:
#      - mysql
#      - keycloak
#    command: ["./wait-for-it.sh"]
#    image: gennyproject/qwanda-service:latest 
#    container_name: qwanda-service 
#    volumes:
#      - ./realm:/opt/realm
#    env_file:
#      - ${ENV_FILE} 
#    environment:
#      - JAVA_OPT_KEYCLOAK_PATH=-Dswarm.keycloak.json.path=/realm/keycloak.json
#    ports:
#      - 8887:8787
#      - 8280:8080
#    links:
#      - mysql:mysql
#      - keycloak:keycloak
#    restart: unless-stopped
#    networks:
#      - mainproxy

  keycloak:
    image: gennyproject/keycloak:working 
    container_name: keycloak 
    env_file:
      - ${ENV_FILE} 
#    environment:
#      - IMPORTEXPORT=EXPORT
#      - KEYCLOAK_USER=admin
#      - KEYCLOAK_PASSWORD=admin
    volumes:
      - ./realm:/tmp/realm 
    networks:
      - mainproxy
    ports:
      - 8180:8080
    command: -b 0.0.0.0  


  kie-server: 
    image: gennyproject/kie-server:latest  
    container_name: kie-server
    environment:
      - MYSQL_DATABASE=kieserverdb
      - MYSQL_PORT_3306_TCP_ADDR=kieserverdb
      - MYSQL_PORT_3306_TCP_PORT=3306
      - MYSQL_USER=genny
      - MYSQL_PASSWORD=password
    ports:
      - 8230:8230
    links:
      - kieserverdb
      - mysql
#      - qwanda-service
      - keycloak
    networks:
      - mainproxy

#  kie-workbench: 
#    image: jboss/jbpm-workbench:latest  
#    container_name: kie-workbench
#    ports:
#      - 8580:8080
#    links:
#      - qwanda-service:qwanda-service
#      - keycloak
#      - kie-server
#    networks:
#      - mainproxy

#  mail:
#    image: tvial/docker-mailserver:latest
#    hostname: mail
#    domainname: domain.com
#    container_name: mail
#    ports:
#    - "25:25"
#    - "143:143"
#    - "587:587"
#    - "993:993"
#    volumes:
#    - maildata:/var/mail
#    - mailstate:/var/mail-state
#    - ./config/:/tmp/docker-mailserver/
#    environment:
#    - ENABLE_SPAMASSASSIN=1
#    - ENABLE_CLAMAV=1
#    - ENABLE_FAIL2BAN=1
#    - ENABLE_POSTGREY=1
#    - ONE_DIR=1
#    - DMS_DEBUG=0
#    cap_add:
#    - NET_ADMIN
#    networks:
#      - mainproxy


volumes:
  mysql_data:
  maildata:
    driver: local
  mailstate:
    driver: local 
networks:
  mainproxy:
    driver: bridge 


