version: '2'
 
services:

#  cassandra:
#    image: tobert/cassandra
#    container_name: cassandra
#    ports:
#      - "9160:9160"
#    networks:
#      - mainproxy
    

  alyson:
    image: gennyproject/alyson:latest
    container_name: alyson 
    depends_on:
      - bridge
    ports:
      - "5000:80"
    env_file:
      - ${ENV_FILE}
    networks:
      - mainproxy
    restart: always

  mysql:
    image: mysql 
    container_name: mysql 
    env_file:
      - ${ENV_FILE} 
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - mainproxy
    ports:
      - 3310:3306 
    restart: unless-stopped

#  kieserverdb:
#    image: mysql:latest
#    container_name: kieserverdb 
#    networks:
#      - mainproxy
#    ports:
#      - 3320:3306
#    environment:
#      - MYSQL_ROOT_PASSWORD=password
#      - MYSQL_DATABASE=kieserverdb
#      - MYSQL_USER=genny
#      - MYSQL_PASSWORD=password

 
 
#  qwanda-service:
#    depends_on:
#      - mysql
#      - keycloak
#    command: ["./wait-for-it.sh"]
#    image: gennyproject/wildfly-qwanda-service:latest 
#    container_name: qwanda-service 
#    volumes:
#      - ./realm:/opt/realm
#    env_file:
#      - ${ENV_FILE} 
#    environment:
#      - JAVA_OPT_KEYCLOAK_PATH=-Dswarm.keycloak.json.path=/realm/keycloak.json
#    ports:
#      - 8887:8787
#      - 8280:8080
#    links:
#      - mysql:mysql
#      - keycloak:keycloak
#    restart: unless-stopped
#    networks:
#      - mainproxy

  qwanda-service:
    depends_on:
      - mysql 
      - keycloak
    image: gennyproject/wildfly-qwanda-service:latest
#    command: ["./wait-for-it.sh"]
    container_name: qwanda-service 
    volumes:
      - ./realm:/realm
    env_file:
      - ${ENV_FILE} 
#    environment:
#      - MYSQL_PORT_3306_TCP_ADDR=gennydb
#      - MYSQL_PORT_3306_TCP_PORT=3306
#      - MYSQL_DATABASE=gennydb
#      - MYSQL_USER=genny
#      - MYSQL_PASSWORD=password
#      - ADMIN_USERNAME=admin
#      - ADMIN_PASSWORD=password
#      - CORS_ALLOWED_ORIGINS="https://genny.outcome-hub.com,http://qwanda-service.outcome-hub.com,https://qwanda-service.outcome-hub.com,http://localhost:58080,http://localhost:3000,http://localhost:5000,http://localhost:8998"
    ports:
      - "8998:8998"
      - "50293:50293"
      - "8280:8080"
      - "8887:8787"
      - "59990:9990"
    links:
      - mysql:mysql
      - keycloak:keycloak
    restart: unless-stopped
    networks:
      - mainproxy

  keycloak:
    image: gennyproject/keycloak:working 
    container_name: keycloak 
    env_file:
      - ${ENV_FILE} 
#    environment:
#      - IMPORTEXPORT=EXPORT
#      - KEYCLOAK_USER=admin
#      - KEYCLOAK_PASSWORD=admin
    volumes:
      - ./realm:/tmp/realm 
    networks:
      - mainproxy
    ports:
      - 8180:8080
    command: -b 0.0.0.0  

#  gennyql:
#    image: gennyproject/gennyql:latest
#    container_name:  gennyql 
#    volumes:
#      - ./realm:/opt/realm
#    env_file:
#      - ${ENV_FILE} 
#    depends_on:
#      - bridge 
#    networks:
#      - mainproxy
#    links:
#      - keycloak
#    ports:
#      - 5704:5704
#      - 15704:15704
#    command: java -Djava.net.preferIPv6Addresses=false -Djava.net.preferIPv4Stack=true -Djava.net.preferIPv4Addresses=true -Dvertx.hazelcast.config=/cluster.xml -DdockerNetworkNames=mainproxy -DdockerServiceNames=gennymain_hazelcast-genny -DhazelcastPeerPort=5701 -jar /service.jar
   

  bridge:
    image: gennyproject/bridge:latest
    container_name: bridge 
    volumes:
      - ./realm:/opt/realm
    env_file:
      - ${ENV_FILE} 
    depends_on:
      - rulesservice
    networks:
      - mainproxy
    links:
      - qwanda-service:qwanda-service
      - keycloak
    ports:
      - 8088:8088  
      - 5701:5701
      - 4001:15701  
    command: java -Djava.net.preferIPv6Addresses=false -Djava.net.preferIPv4Stack=true -Djava.net.preferIPv4Addresses=true -Dvertx.hazelcast.config=/cluster.xml -DdockerNetworkNames=mainproxy -DdockerServiceNames=gennymain_hazelcast-genny -DhazelcastPeerPort=5701 -jar /service.jar
   
  rulesservice:
    image: gennyproject/rulesservice:latest
    container_name:  rulesservice 
    volumes:
      - ./realm:/opt/realm
      - ./rules:/rules
    links:
      # - bridge:bridge
      - qwanda-service:qwanda-service
      - keycloak
    env_file:
      - ${ENV_FILE} 
    ports:
      - 5702:5702
      - 4002:15702  
    # depends_on:
      # - bridge 
      # - qwanda-service
    networks:
      - mainproxy
    restart: always
    command: java -Djava.net.preferIPv6Addresses=false -Djava.net.preferIPv4Stack=true -Djava.net.preferIPv4Addresses=true -Dvertx.hazelcast.config=/cluster.xml -DdockerNetworkNames=mainproxy -DdockerServiceNames=gennymain_hazelcast-genny -DhazelcastPeerPort=5701 -jar /service.jar

#  social:
#    image: gennyproject/social:latest
#    container_name: social 
#    volumes:
#      - ./realm:/opt/realm
#    env_file:
#      - ${ENV_FILE} 
#    networks:
#      - mainproxy
#    links:
#      - qwanda-service:qwanda-service
#      - keycloak
#    ports:
#      - 8083:8083    
#    command: java -Djava.net.preferIPv6Addresses=false -Djava.net.preferIPv4Stack=true -Djava.net.preferIPv4Addresses=true -Dvertx.hazelcast.config=/cluster.xml -DdockerNetworkNames=mainproxy -DdockerServiceNames=gennymain_hazelcast-genny -DhazelcastPeerPort=5701 -jar /service.jar
#
#  scoring:
#    image: gennyproject/scoring:latest
#    container_name: scoring 
#    volumes:
#      - ./realm:/opt/realm
#    env_file:
#      - ${ENV_FILE} 
#    networks:
#      - mainproxy
#    links:
#      - qwanda-service:qwanda-service
#      - keycloak
#    ports:
#      - 8085:8085    
#    command: java -Djava.net.preferIPv6Addresses=false -Djava.net.preferIPv4Stack=true -Djava.net.preferIPv4Addresses=true -Dvertx.hazelcast.config=/cluster.xml -DdockerNetworkNames=mainproxy -DdockerServiceNames=gennymain_hazelcast-genny -DhazelcastPeerPort=5701 -jar /service.jar
#   
#  kieclient: 
#    image: gennyproject/kieclient:latest  
#    container_name: kieclient
#    links:
#      - kie-server 
#      - keycloak
#    env_file:
#      - ${ENV_FILE} 
#    volumes:
#      - ./realm:/opt/realm
#    depends_on:
#      - kie-server 
#    ports:
#      - 5703:5703
#      - 4003:15703 
#    networks:
#      - mainproxy
#    command: java -Djava.net.preferIPv6Addresses=false -Djava.net.preferIPv4Stack=true -Djava.net.preferIPv4Addresses=true -Dvertx.hazelcast.config=/cluster.xml -DdockerNetworkNames=mainproxy -DdockerServiceNames=gennymain_hazelcast-genny -DhazelcastPeerPort=5701 -jar /service.jar

#  kie-server: 
#    image: gennyproject/kie-server:latest  
#    container_name: kie-server
#    ports:
#      - 8230:8230
#    links:
#      - qwanda-service
#      - keycloak
#      - kieserverdb
#    networks:
#      - mainproxy
#
#  kie-workbench: 
#    image: gennyproject/kie-wb:latest  
#    container_name: kie-workbench
#    ports:
#      - 8580:8080
#    links:
#      - qwanda-service:qwanda-service
#      - keycloak
#      - kie-server
#    networks:
#      - mainproxy

#  mail:
#    image: tvial/docker-mailserver:latest
#    hostname: mail
#    domainname: domain.com
#    container_name: mail
#    ports:
#    - "25:25"
#    - "143:143"
#    - "587:587"
#    - "993:993"
#    volumes:
#    - maildata:/var/mail
#    - mailstate:/var/mail-state
#    - ./config/:/tmp/docker-mailserver/
#    environment:
#    - ENABLE_SPAMASSASSIN=1
#    - ENABLE_CLAMAV=1
#    - ENABLE_FAIL2BAN=1
#    - ENABLE_POSTGREY=1
#    - ONE_DIR=1
#    - DMS_DEBUG=0
#    cap_add:
#    - NET_ADMIN
#    networks:
#      - mainproxy


volumes:
  mysql_data:
  maildata:
    driver: local
  mailstate:
    driver: local 
networks:
  mainproxy:
    driver: bridge 


