version: '2.0'

services:
  bsb-lookup:
    image: gennyproject/bsb-lookup:latest
    container_name: bsb-lookup
    ports:
      - 3333:3333
    networks:
      - mainproxy
    restart: always

  
#  gennyql:
#    image: gennyproject/gennyql
#    container_name: gennyql
#    networks:
#      - mainproxy
#    ports:
#      - "8083:8084"
#    restart: always
#    command: java -jar /service.jar

  nginx:
    image: jwilder/nginx-proxy:latest
    container_name: nginx 
  #  image: nginx:alpine
  #  labels:
  #      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    hostname: nginx
    ports:
      - 80:80
      - 443:443
    networks:
      - mainproxy
    environment:
      - SKIP_HTTPS_REDIRECT=false
    volumes:
      - ./nginx/conf.d2:/etc/nginx/conf.d
      - ./nginx/vhost.d:/etc/nginx/vhost.d
      - ./nginx/html:/usr/share/nginx/html
      - ./nginx/certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro

  imageproxy:
    image: willnorris/imageproxy:v0.7.0
    container_name: image_proxy
    ports:
      - "46243:8080"
    command: -cache /tmp/imageproxy -addr 0.0.0.0:8080 -scaleUp true


  alyson:
    image: gennyproject/alyson:latest
#    container_name: alyson
#    ports:
#      - "5000:80"
    environment:
      - REACT_BRIDGE_HOST=http://bridge.genny.life
      - VIRTUAL_PORT=80
      - VIRTUAL_HOST=local.*,alyson.*,v2.*
      - VIRTUAL_PROTO=http
      - CERT_NAME=genny.life
    env_file:
      - ${ENV_FILE}
    networks:
      - mainproxy
    restart: always

  mysql:
    #image: channel40/mysql:latest2 
    image: mariadb
    environment:
      - MYSQL_URL=mysql
      - MYSQL_DB=gennydb
      - MYSQL_PORT=3306
      - MYSQL_ALLOW_EMPTY=
      - MYSQL_RANDOM_ROOT_PASSWORD=no
      - MYSQL_DATABASE=gennydb
      - MYSQL_USER=genny
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=password
    container_name: mysql
    env_file:
      - ${ENV_FILE}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - mainproxy
    ports:
      - 3310:3306
    restart: unless-stopped

  keycloak:
    image: gennyproject/keycloak:latest
    container_name: keycloak
    env_file:
      - ${ENV_FILE}
    environment:
      - VIRTUAL_HOST=keycloak.*,bouncer.*
      - VIRTUAL_PORT=8080
      - VIRTUAL_PROTO=http
      - CERT_NAME=genny.life
#      - IMPORTEXPORT=EXPORT
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=Outcome2016KeycloakAdmin
      - MYSQL_URL=mysql
      - MYSQL_PORT=3306
      - MYSQL_DB=keycloakdb
      - MYSQL_USERNAME=keycloak
      - MYSQL_PASSWORD=Outcome2016KeycloakAdmin
    volumes:
      - ../keycloak-themes/themes:/opt/jboss/keycloak/themes
      - ./realm:/tmp/realm
    networks:
      - mainproxy
    ports:
      - 8180:8080
    command: -b 0.0.0.0



  qwanda-service:
    depends_on:
      - mysql
      - keycloak
    image: gennyproject/wildfly-qwanda-service:latest
    #image: gennyproject/wildfly-qwanda-service:jrebel
    container_name: qwanda-service
    volumes:
      - ./realm:/opt/realm
      - ./google_credentials:/root/.genny/sheets.googleapis.com-java-quickstart/
    env_file:
      - ${ENV_FILE}
    environment:
      - VIRTUAL_HOST=qwanda-service.*,api.*
      - VIRTUAL_PORT=8080
      - VIRTUAL_PROTO=http
      - CERT_NAME=genny.life
      - SKIP_GOOGLE_DOC_IN_STARTUP=TRUE
    ports:
      - "8280:8080"
      - "8887:8787"
  #    - "5706:5701"
    links:
      - mysql:mysql
      - keycloak:keycloak
    restart: unless-stopped
    networks:
      - mainproxy

  payments:
     image: gennyproject/payments:latest
     container_name: payments
     env_file:
      - ${ENV_FILE}
     environment:
      - VIRTUAL_HOST=payments2.genny.life
      - VIRTUAL_PORT=3456
      - VIRTUAL_PROTO=http
      - CERT_NAME=genny.life
     ports:
#       - "3456:3456"
      - "6543 :6543"
     networks:
       - mainproxy

  layout-cache:
    image: gennyproject/layout-cache:latest
    container_name: layout-cache
    environment:
      - LAYOUT_REPO=https://github.com/genny-project/layouts.git
      - NODE_ENV=dev
      - VIRTUAL_HOST=layout-cache.genny.life
      - VIRTUAL_PORT=2223
      - VIRTUAL_PROTO=http
      - CERT_NAME=genny.life
#    ports:
#      - "2223:2223"
    networks:
      - mainproxy

  camelot-pdfgenerator:
    image: matthayward1997/camelot:latest
    container_name: camelot-pdfgenerator
    ports:
      - "7331:7331"
    networks:
      - mainproxy

  uppy:
     image: gennyproject/uppy:latest
     container_name: uppy
     env_file:
      - ${ENV_FILE}
     environment:
      - VIRTUAL_HOST=uppy.genny.life
      - VIRTUAL_PORT=3020
      - VIRTUAL_PROTO=http
      - CERT_NAME=genny.life
#     ports:
#       - "3020:3020"
     networks:
       - mainproxy


volumes:
  mysql_data:
  maildata:
    driver: local
  mailstate:
    driver: local
networks:
  mainproxy:
    driver: bridge
