version: '2'

services:
  nginx:
    image: jwilder/nginx-proxy:latest
    hostname: nginx
    ports:
      - 80:80
      - 443:443
    networks:
      - mainproxy
    environment:
      - SKIP_HTTPS_REDIRECT=true
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/vhost.d:/etc/nginx/vhost.d
      - ./nginx/html:/usr/share/nginx/html
      - ./nginx/certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro

  in-app-call-server:
    image: gennyproject/in-app-call-server
    container_name: in-app-call-server
    ports:
      - "2255:2255"
    env_file:
      - ${ENV_FILE}

  imageproxy:
    image: willnorris/imageproxy:v0.7.0
    ports:
      - "46243:8080"
    command: -cache /tmp/imageproxy -addr 0.0.0.0:8080 -scaleUp true


  bsb-lookup:
    image: gennyproject/bsb-lookup:latest
    container_name: bsb-lookup
    ports:
      - 3333:3333
    networks:
      - mainproxy
    restart: always


  alyson:
    image: gennyproject/alyson:latest
    container_name: alyson
    depends_on:
      - bridge
    ports:
      - "5000:80"
    environment:
      - REACT_BRIDGE_HOST=http://bridge.genny.life
      - VIRTUAL_PORT=80
      - VIRTUAL_HOST=local.*,alyson.*,v2.*
      - VIRTUAL_PROTO=http
      - CERT_NAME=genny.life
      - NODE_ENV=staging
    env_file:
      - ${ENV_FILE}
    networks:
      - mainproxy
    restart: always

  mysql:
    image: mysql:5.6 
    environment:
      - MYSQL_URL=mysql
      - MYSQL_DB=gennydb
      - MYSQL_PORT=3306
      - MYSQL_ALLOW_EMPTY=
      - MYSQL_RANDOM_ROOT_PASSWORD=no
      - MYSQL_DATABASE=gennydb
      - MYSQL_USER=genny
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=password
    container_name: mysql
    env_file:
      - ${ENV_FILE}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - mainproxy
    ports:
      - 3310:3306
    restart: unless-stopped


  signatures:
    image: gennyproject/signatures:latest
    environment:
      - S3_BUCKET=${S3_BUCKET}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    ports:
      - "7446:7446"

  qwanda-service:
    depends_on:
      - mysql
      - keycloak
    image: gennyproject/wildfly-qwanda-service:latest
    container_name: qwanda-service
    volumes:
      - ./realm:/opt/realm
      - ./google_credentials:/root/.genny/sheets.googleapis.com-java-quickstart/
    env_file:
      - ${ENV_FILE}
    environment:
      - VIRTUAL_HOST=qwanda-service.*,api.*
      - VIRTUAL_PORT=8080
      - VIRTUAL_PROTO=http
      - CERT_NAME=genny.life
      - LOAD_DDT_IN_STARTUP=TRUE
      - SKIP_GOOGLE_DOC_IN_STARTUP=FALSE
  #    - DEV_MODE=TRUE
      - DDTHOST=TRUE
      - DDT_URL=http://bridge:8089 
    ports:
      - "8280:8080"
      - "8887:8787"
    links:
      - mysql:mysql
      - keycloak:keycloak
    restart: unless-stopped
    networks:
      - mainproxy

  keycloak:
    image: gennyproject/keycloak:latest
    container_name: keycloak
    env_file:
      - ${ENV_FILE}
    environment:
      - VIRTUAL_HOST=keycloak.*,bouncer.*
      - VIRTUAL_PORT=8080
      - VIRTUAL_PROTO=http
      - CERT_NAME=genny.life
#      - IMPORTEXPORT=EXPORT
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=Outcome2016KeycloakAdmin
      - MYSQL_URL=mysql
      - MYSQL_PORT=3306
      - MYSQL_DB=keycloakdb
      - MYSQL_USERNAME=keycloak
      - MYSQL_PASSWORD=Outcome2016KeycloakAdmin
    volumes:
#      - /opt/jboss/backup:/opt/jboss/backup
      - ../keycloak-themes/themes:/opt/jboss/keycloak/themes
      - ./realm:/tmp/realm
      #- ./realm:/tmp/realm
      #- ./keycloak-themes/themes:/opt/jboss/keycloak/themes
    networks:
      - mainproxy
    ports:
      - 8180:8080
    command: -b 0.0.0.0

  bridge:
    image: gennyproject/bridge:latest
    container_name: bridge
    volumes:
      - ./realm:/opt/realm
    env_file:
      - ${ENV_FILE}
    environment:
      - VIRTUAL_HOST=bridge.genny.life
      - VIRTUAL_PORT=8088
      - VIRTUAL_PROTO=http
      - CERT_NAME=genny.life
      - DDTHOST=TRUE
      - API_PORT=8088
      - CACHE_API_PORT=8089
      - DDT_URL=http://bridge:8089
  #    - DEV_MODE=TRUE
  #    - GENNYDEV=TRUE
  #    - GENNY_DEV=TRUE
    networks:
      - mainproxy
    links:
      - qwanda-service:qwanda-service
      - keycloak
    ports:
      - 8088:8088
      - 8790:8787
#      - 5701:5701
#      - 4001:15701
  #  command: java  -Dvertx.metrics.options.enabled=true -Dhazelcast.diagnostics.enabled=true  -Dvertx.options.blockedThreadCheckInterval=2147483647 -jar /service.jar  -cluster
    command: java  -Xdebug -Xrunjdwp:transport=dt_socket,address=8787,server=y,suspend=n  -Dvertx.metrics.options.enabled=true -Dvertx.options.blockedThreadCheckInterval=2147483647 -jar /service.jar -cluster

  rulesservice:
    image: gennyproject/rulesservice:latest
    container_name:  rulesservice
    volumes:
      - ./realm:/opt/realm
#      - ./rules:/rules2
#      - ./rules:/rules/rulesCurrent
    links:
      - bridge:bridge
      - qwanda-service:qwanda-service
      - keycloak
    environment:
      - RULES_DIR=/rules
      - VIRTUAL_PORT=8089
      - CACHE_API_PORT=8089
      - VIRTUAL_PROTO=http
      - CERT_NAME=genny.life
  #    - DEV_MODE=TRUE
      - RULESMANAGER=TRUE
      - DDTHOST=TRUE
      - DDT_URL=http://bridge:8089
  #    - GENNYDEV=TRUE
    env_file:
      - ${ENV_FILE}
    ports:
      - 8997:8787
      - 8089:8089
#      - 8880:8080
#      - 5702:5702
#      - 4002:15702

    depends_on:
      - messages
      - bridge
      - qwanda-service
    networks:
      - mainproxy
    restart: always
    command: java  -Xdebug -Xrunjdwp:transport=dt_socket,address=8787,server=y,suspend=n  -Dvertx.options.blockedThreadCheckInterval=2147483647 -jar /service.jar -cluster

  social:
    image: gennyproject/social:latest
    container_name: social
    volumes:
      - ./realm:/opt/realm
    env_file:
      - ${ENV_FILE}
    environment:
      - VIRTUAL_HOST=social.genny.life
      - VIRTUAL_PORT=8083
      - VIRTUAL_PROTO=http
      - CERT_NAME=genny.life
      - DDT_URL=http://bridge:8089
    networks:
      - mainproxy
    links:
      - qwanda-service:qwanda-service
      - keycloak
    depends_on:
      - qwanda-service
    ports:
      - 8083:8083
      - 8788:8787
    command: java -Djava.net.preferIPv6Addresses=false -Djava.net.preferIPv4Stack=true  -Xdebug -Xrunjdwp:transport=dt_socket,address=8787,server=y,suspend=n -Djava.net.preferIPv4Addresses=true -Dvertx.hazelcast.config=/cluster.xml -DdockerNetworkNames=mainproxy -DdockerServiceNames=gennymain_hazelcast-genny -DhazelcastPeerPort=5701 -jar /service.jar


  messages:
    image: gennyproject/messages:latest
    container_name:  messages
    volumes:
      - ./realm:/opt/realm
      - ./google_credentials:/root/.genny/sheets.googleapis.com-java-quickstart/
      - ./google_credentials/drive:/root/.genny/credentials/credentials-genny/drive/
    links:
      - qwanda-service:qwanda-service
      - keycloak
    env_file:
      - ${ENV_FILE}
    environment:
      - DDT_URL=http://bridge:8089
    ports:
      - 5709:5709
      - 4003:15709
      - 8789:8787
    depends_on:
      - bridge
      - qwanda-service
    networks:
      - mainproxy
    restart: always
    command: java  -Xdebug -Xrunjdwp:transport=dt_socket,address=8787,server=y,suspend=n -Djava.net.preferIPv6Addresses=false -Djava.net.preferIPv4Stack=true -Djava.net.preferIPv4Addresses=true -Dvertx.hazelcast.config=/cluster.xml -DdockerNetworkNames=mainproxy -DdockerServiceNames=gennymain_hazelcast-genny -DhazelcastPeerPort=5701 -jar /service.jar

  payments:
     image: gennyproject/payments:latest
     container_name: payments
     env_file:
      - ${ENV_FILE}
     environment:
      - VIRTUAL_HOST=payments2.genny.life
      - VIRTUAL_PORT=3456
      - VIRTUAL_PROTO=http
      - CERT_NAME=genny.life
     ports:
      - "3456:3456"
      - "6543:6543"
 
     networks:
       - mainproxy

  uppy:
     image: gennyproject/uppy:latest
     container_name: uppy
     env_file:
      - ${ENV_FILE}
     environment:
      - VIRTUAL_HOST=uppy.genny.life
      - VIRTUAL_PORT=3020
      - VIRTUAL_PROTO=http
      - CERT_NAME=genny.life
#     ports:
#       - "3020:3020"
     networks:
       - mainproxy

  layout-cache:
    image: gennyproject/layout-cache:latest
    container_name: layout-cache
    environment:
      - LAYOUT_REPO=https://github.com/genny-project/layouts.git
      - NODE_ENV=dev
      - VIRTUAL_HOST=layout-cache.genny.life
      - VIRTUAL_PORT=2223
      - VIRTUAL_PROTO=http
      - CERT_NAME=genny.life
      - GIT_SSH=${GIT_SSH}
      - SSH_PRIVATE_KEY=${SSH_PRIVATE_KEY}
#    ports:
#      - "2223:2223"
    networks:
      - mainproxy

  camelot-pdfgenerator:
    image: matthayward1997/camelot:latest
    container_name: camelot-pdfgenerator
    ports:
      - "7331:7331"
    networks:
      - mainproxy

volumes:
  mysql_data:
  maildata:
    driver: local
  mailstate:
    driver: local
networks:
  mainproxy:
    driver: bridge

#
