version: '2'

services:
  imageproxy:
    image: willnorris/imageproxy:v0.7.0
    ports:
      - "46243:8080"
    command: -cache /tmp/imageproxy -addr 0.0.0.0:8080 -scaleUp true

#  cassandra:
#    image: tobert/cassandra
#    container_name: cassandra
#    ports:
#      - "9160:9160"
#    networks:
#      - mainproxy

#  gennyql:
#    image: gennyproject/gennyql
#    container_name: gennyql
#    networks:
#      - mainproxy
#    ports:
#      - "8084:8084"
#    restart: always
#    command: java -jar /service.jar


#  bsb-lookup:
#    image: gennyproject/bsb-lookup:latest
#    container_name: bsb-lookup
#    ports:
#      - 3333:3333
#    networks:
#      - mainproxy
#    restart: always

#  alyson-dev:
#    image: gennyproject/alyson:dev
#    container_name: alyson-dev
#    depends_on:
#      - bridge
#    ports:
#      - "15000:80"
#    env_file:
#      - ${ENV_FILE}
#    networks:
#      - mainproxy
#    restart: always

  alyson:
    image: gennyproject/alyson:latest
    container_name: alyson
    depends_on:
      - bridge
    ports:
      - "5000:80"
    env_file:
      - ${ENV_FILE}
    networks:
      - mainproxy
    restart: always

  mysql:
    image: mariadb
    environment:
      - MYSQL_URL=mysql
      - MYSQL_DB=gennydb
      - MYSQL_PORT=3306
      - MYSQL_ALLOW_EMPTY=
      - MYSQL_RANDOM_ROOT_PASSWORD=no
      - MYSQL_DATABASE=gennydb
      - MYSQL_USER=genny
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=password
    container_name: mysql
    env_file:
      - ${ENV_FILE}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - mainproxy
    ports:
      - 3310:3306
    restart: unless-stopped

#  kieserverdb:
#    image: mysql:latest
#    container_name: kieserverdb
#    networks:
#      - mainproxy
#    ports:
#      - 3320:3306
#    environment:
#      - MYSQL_ROOT_PASSWORD=password
#      - MYSQL_DATABASE=kieserverdb
#      - MYSQL_USER=genny
#      - MYSQL_PASSWORD=password




  qwanda-service:
    depends_on:
      - mysql
      - keycloak
    image: gennyproject/wildfly-qwanda-service:latest
    container_name: qwanda-service
    volumes:
      - ./realm:/opt/realm
      - ./google_credentials:/root/.genny/sheets.googleapis.com-java-quickstart/
    env_file:
      - ${ENV_FILE}
#    environment:
#      - MYSQL_PORT_3306_TCP_ADDR=gennydb
#      - MYSQL_PORT_3306_TCP_PORT=3306
#      - MYSQL_DATABASE=gennydb
#      - MYSQL_USER=genny
#      - MYSQL_PASSWORD=password
#      - ADMIN_USERNAME=admin
#      - ADMIN_PASSWORD=password
#      - CORS_ALLOWED_ORIGINS="https://genny.outcome-hub.com,http://qwanda-service.outcome-hub.com,https://qwanda-service.outcome-hub.com,http://localhost:58080,http://localhost:3000,http://localhost:5000,http://localhost:8998"
    ports:
      - "8280:8080"
      - "8887:8787"
    links:
      - mysql:mysql
      - keycloak:keycloak
    restart: unless-stopped
    networks:
      - mainproxy

  keycloak:
    image: gennyproject/keycloak:latest
    container_name: keycloak
    env_file:
      - ${ENV_FILE}
    environment:
#      - IMPORTEXPORT=EXPORT
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=Outcome2016KeycloakAdmin
      - MYSQL_URL=mysql
      - MYSQL_PORT=3306
      - MYSQL_DB=keycloakdb
      - MYSQL_USERNAME=keycloak
      - MYSQL_PASSWORD=Outcome2016KeycloakAdmin
    volumes:
#      - /opt/jboss/backup:/opt/jboss/backup
      - ../keycloak-themes/themes:/opt/jboss/keycloak/themes
      - ./realm:/tmp/realm
      #- ./realm:/tmp/realm
      #- ./keycloak-themes/themes:/opt/jboss/keycloak/themes
    networks:
      - mainproxy
    ports:
      - 8180:8080
    command: -b 0.0.0.0

  bridge:
    image: gennyproject/bridge:latest
#    container_name: bridge
    volumes:
      - ./realm:/opt/realm
    env_file:
      - ${ENV_FILE}
    networks:
      - mainproxy
    links:
      - qwanda-service:qwanda-service
      - keycloak
    ports:
      - 8088:8088
#      - 5701:5701
#      - 4001:15701
    command: java -Dvertx.metrics.options.enabled=true -Dvertx.options.blockedThreadCheckInterval=2147483647 -jar /service.jar -cluster

  rulesservice:
    image: gennyproject/rulesservice:latest
#    container_name:  rulesservice
    volumes:
      - ./realm:/opt/realm
#      - ./rules:/rules
      - ./rules:/rules2
    links:
      - bridge:bridge
      - qwanda-service:qwanda-service
      - keycloak
    environment:
      -  RULES_DIR=/rules
    env_file:
      - ${ENV_FILE}
#    ports:
#       - 8089:8089
#      - 8880:8080
#      - 5702:5702
#      - 4002:15702
    depends_on:
      - messages
      - bridge
      - qwanda-service
    networks:
      - mainproxy
    restart: always
    command: java  -Dvertx.options.blockedThreadCheckInterval=2147483647 -jar /service.jar -cluster

  social:
    image: gennyproject/social:latest
    container_name: social
    volumes:
      - ./realm:/opt/realm
    env_file:
      - ${ENV_FILE}
    networks:
      - mainproxy
    links:
      - qwanda-service:qwanda-service
      - keycloak
    depends_on:
      - qwanda-service
    ports:
      - 8083:8083
    command: java -Djava.net.preferIPv6Addresses=false -Djava.net.preferIPv4Stack=true -Djava.net.preferIPv4Addresses=true -Dvertx.hazelcast.config=/cluster.xml -DdockerNetworkNames=mainproxy -DdockerServiceNames=gennymain_hazelcast-genny -DhazelcastPeerPort=5701 -jar /service.jar


#  kie-server:
#    image: gennyproject/kie-server:latest
#    container_name: kie-server
#    ports:
#      - 8230:8230
#    links:
#      - qwanda-service
#      - keycloak
#      - kieserverdb
#    networks:
#      - mainproxy
#
#  kie-workbench:
#    image: gennyproject/kie-wb:latest
#    container_name: kie-workbench
#    ports:
#      - 8580:8080
#    links:
#      - qwanda-service:qwanda-service
#      - keycloak
#      - kie-server
#    networks:
#      - mainproxy

#  mail:
#    image: tvial/docker-mailserver:latest
#    hostname: mail
#    domainname: domain.com
#    container_name: mail
#    ports:
#    - "25:25"
#    - "143:143"
#    - "587:587"
#    - "993:993"
#    volumes:
#    - maildata:/var/mail
#    - mailstate:/var/mail-state
#    - ./config/:/tmp/docker-mailserver/
#    environment:
#    - ENABLE_SPAMASSASSIN=1
#    - ENABLE_CLAMAV=1
#    - ENABLE_FAIL2BAN=1
#    - ENABLE_POSTGREY=1
#    - ONE_DIR=1
#    - DMS_DEBUG=0
#    cap_add:
#    - NET_ADMIN
#    networks:
#      - mainproxy

  messages:
    image: gennyproject/messages:latest
    container_name:  messages
    volumes:
      - ./realm:/opt/realm
      - ./google_credentials:/root/.genny/sheets.googleapis.com-java-quickstart/
      - ./google_credentials/drive:/root/.genny/credentials/credentials-genny/drive/
    links:
      - qwanda-service:qwanda-service
      - keycloak
    env_file:
      - ${ENV_FILE}
    ports:
      - 5709:5709
      - 4003:15709
    depends_on:
      - bridge
      - qwanda-service
    networks:
      - mainproxy
    restart: always
    command: java -Djava.net.preferIPv6Addresses=false -Djava.net.preferIPv4Stack=true -Djava.net.preferIPv4Addresses=true -Dvertx.hazelcast.config=/cluster.xml -DdockerNetworkNames=mainproxy -DdockerServiceNames=gennymain_hazelcast-genny -DhazelcastPeerPort=5701 -jar /service.jar

  payments:
     image: gennyproject/payments:latest
     container_name: payments
     env_file:
      - ${ENV_FILE}
     ports:
       - "3456:3456"
     networks:
       - mainproxy

  uppy:
     image: gennyproject/uppy:latest
     container_name: uppy
     env_file:
       - ${ENV_FILE}
     ports:
       - "3020:3020"
     networks:
       - mainproxy

  layout-cache:
    image: gennyproject/layout-cache:latest
    container_name: layout-cache
    environment:
      - LAYOUT_REPO=https://github.com/genny-project/layouts.git
      - NODE_ENV=production
    ports:
      - "2223:2223"
    networks:
      - mainproxy

  camelot-pdfgenerator:
    image: matthayward1997/camelot:latest
    container_name: camelot-pdfgenerator
    ports:
      - "7331:7331"
    networks:
      - mainproxy

volumes:
  mysql_data:
  maildata:
    driver: local
  mailstate:
    driver: local
networks:
  mainproxy:
    driver: bridge

#
